apiVersion: 'v1'
kind: Service
metadata:
  name: "postgres-db"
  labels:
    app: "postgres-db"
    tier: "database"
spec:
  ports:
    - port: 5432
  selector:
    app: "postgres-db"
    tier: "database"
  clusterIP: None

---
apiVersion: 'v1'
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgres-db"
  labels:
    app: "postgres-db"
    tier: "database"
spec:
  selector:
    matchLabels:
      app: "postgres-db"
      tier: "database"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
        tier: database
    spec:
      containers:
        - name: "postgres-db"
          image: "postgres:13.1-alpine"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: name
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-persistance-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistance-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim



